//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        public DATHANG()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
        }
    
        public string MADATHANG { get; set; }
        public string TENDN { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<bool> THANHTOAN { get; set; }
        public string DIACHIGIAOHANG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string TENNGUOINHAN { get; set; }
        public string SDTNHAN { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
