//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public string MAGH { get; set; }
        public string TENDN { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SOLUONGSP { get; set; }
        public Nullable<bool> THANHTOAN { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
