//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        public NHAPHANG()
        {
            this.CHITIETNHAPHANGs = new HashSet<CHITIETNHAPHANG>();
        }
    
        public string MANHAPHANG { get; set; }
        public Nullable<decimal> TONGCHIPHI { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string MANCC { get; set; }
        public Nullable<bool> THANHTOAN { get; set; }
    
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANGs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
