//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMNGUOIDUNG
    {
        public NHOMNGUOIDUNG()
        {
            this.NGUOIDUNG_NHOMNGUOIDUNG = new HashSet<NGUOIDUNG_NHOMNGUOIDUNG>();
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
        }
    
        public string MANHOMNGUOIDUNG { get; set; }
        public string TENNHOMNGUOIDUNG { get; set; }
    
        public virtual ICollection<NGUOIDUNG_NHOMNGUOIDUNG> NGUOIDUNG_NHOMNGUOIDUNG { get; set; }
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
