//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.CHITIETNHAPHANGs = new HashSet<CHITIETNHAPHANG>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public Nullable<decimal> GIATRI { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string HINHANH { get; set; }
        public string MALOAISP { get; set; }
        public string MACHATLIEU { get; set; }
        public string MANSX { get; set; }
        public string MANCC { get; set; }
        public Nullable<decimal> KHUYENMAI { get; set; }
    
        public virtual CHATLIEU CHATLIEU { get; set; }
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANGs { get; set; }
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
